### ISSUE TITLE
credential incorrect

### ISSUE THREAD

**Issue by ccrxf** [mkantor/docker-pushmi-pullyu#34] opened 2022-07-21 21:30 UTC
This line of code arised an error - wait-for check-registry "$registry_host:$registry_port"
Previously I tried running this script and it worked, but now an error happens. As a way of dubugging, I tried logging in with your provided credentials - docker login --username="AzureDiamond" --password="hunter2" - on dockerhub, and it showed that the password is wrong. May I know if you had changed your password?

**Comment by mkantor** [comment] 2022-07-21 22:45
This isn't _my_ password (it's actually an [old joke](https://knowyourmeme.com/memes/hunter2)).

The purpose of this `docker login` call is to determine when your local registry instance is up and running—no matter what credentials are provided, the `docker login` command would exit with a nonzero exit status before that point and exit with zero once the registry's HTTP server starts accepting connections. The login call is hitting [the local registry instance that this script runs on your machine](https://github.com/mkantor/docker-pushmi-pullyu/blob/12d28932df0fda7c20cbe899820eaabce6b44997/docker-pushmi-pullyu#L121-L140), not dockerhub.

Unfortunately I don't have time to investigate this right now and am about to go on vacation, but I'll take a look when I return. In the meantime if you can share more details I'd appreciate it. For example: the exact command-line invocation you used, the complete output of `docker-pushmi-pullyu`, what OS you use, the versions of the docker CLI and docker engine that you have installed, etc. And since you said it previously worked, if you made any changes to your system between then and now (e.g. upgrading docker), that would be great to know as well.

**Comment by mkantor** [comment] 2022-08-03 13:15
@ccrxf can you share more details so that I may reproduce the issue?

> For example: the exact command-line invocation you used, the complete output of docker-pushmi-pullyu, what OS you use, the versions of the docker CLI and docker engine that you have installed, etc. And since you said it previously worked, if you made any changes to your system between then and now (e.g. upgrading docker), that would be great to know as well.

**Comment by mkantor** [comment] 2022-08-20 18:50
I haven't been able to reproduce this, so I'm going to close the issue.

@ccrxf feel free to reopen if you're still having trouble. Please share additional details if you do.

**Closed as completed by mkantor** 2022-08-20 18:50 UTC
